### ISSUE TITLE
Not working in Cura 4.13Beta

### ISSUE THREAD

**Issue by kravviec** [jjgraphix/PressureAdvanceSettingPlugin#2]
can't find any pressure advance command in g-code from Cura 4.13 so I created M900 macro, with K-factor from Marlin's  linear advance plugin

**Comment by auditor3d** [comment]
also Cura 5.0 Beta.

**Comment by jjgraphix** [comment]
> can't find any pressure advance command in g-code from Cura 4.13 so I created M900 macro, with K-factor from Marlin's linear advance plugin

I have finally had some time to work on this and will be pushing an update soon containing a number of improvements. While I believe the original version did work in 4.13, the new version fixes a few bugs that may be contributing to this problem.

> also Cura 5.0 Beta.

Thanks, I briefly looked at the 5.0 Beta and see a number of issues with plugins. I'll will do what I can to get it working and will confirm whether or not it is compatible in the update notes.

Check back in the next day or so.

**Comment by jjgraphix** [comment]
Ok well that took longer than expected but the latest release is finally live. I've confirmed it working with all recent versions of Cura, including the latest 5.0 official release. I'll consider this issue closed.
