### ISSUE TITLE
Pressure Advance command always sent / make it selectable

### ISSUE THREAD

**Issue by AndreasALu** [jjgraphix/PressureAdvanceSettingPlugin#3]
Hi. 

your plugin is very helpful, thanks for the work you put into it! 

I use Cura with different printers, some of them do not understand the SET_PRESSURE_ADVANCE line in the G-Code and stop printing.

I tried doing a search & replace postprocessing to delete the SET_PRESSURE_ADVANCE command, but it seems that the line gets inserted after the post processing. So no luck.

Would it be possible to add a setting where you can turn on/off the PA setting per "print setting" and thus the SET_PRESSURE_ADVANCE does not get inserted (and on Klipper printers the Pressure Advance setting of the printer.cfg is used)? This would also prevent existing profiles (where one forgets to update the PA settings) overwriting the printer.cfg setting ;-)

Or could you run the PlugIn before Post Processing is done? The Post Processing scripts are stored per printer, so it would work.

Thx a lot!

**Comment by jjgraphix** [comment]
Thank you, I finally had a chance to resolve this issue in the latest release. When **Enable Pressure Advance Control** is disabled no new lines are inserted into gcode so it should not conflict with other firmware. 

Let me know if you run into other issues.
